lib: [
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/META" {"META"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/compiler/Analysis.re" {"compiler/Analysis.re"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/compiler/BitcoinCompiler.cmi" {"compiler/BitcoinCompiler.cmi"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/compiler/BitcoinCompiler.cmt" {"compiler/BitcoinCompiler.cmt"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/compiler/BitcoinCompiler.cmx" {"compiler/BitcoinCompiler.cmx"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/compiler/BitcoinCompiler.re" {"compiler/BitcoinCompiler.re"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/compiler/Utils.re" {"compiler/Utils.re"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/compiler/bitcoin.compiler.dune" {"compiler/bitcoin.compiler.dune"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/compiler/bitcoinCompiler.a" {"compiler/bitcoinCompiler.a"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/compiler/bitcoinCompiler.cma" {"compiler/bitcoinCompiler.cma"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/compiler/bitcoinCompiler.cmxa" {"compiler/bitcoinCompiler.cmxa"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/compiler/bitcoinCompiler.cmxs" {"compiler/bitcoinCompiler.cmxs"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/compiler/bitcoinCompiler__.cmi" {"compiler/bitcoinCompiler__.cmi"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/compiler/bitcoinCompiler__.cmt" {"compiler/bitcoinCompiler__.cmt"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/compiler/bitcoinCompiler__.cmx" {"compiler/bitcoinCompiler__.cmx"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/compiler/bitcoinCompiler__.ml" {"compiler/bitcoinCompiler__.ml"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/compiler/bitcoinCompiler__Analysis.cmi" {"compiler/bitcoinCompiler__Analysis.cmi"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/compiler/bitcoinCompiler__Analysis.cmt" {"compiler/bitcoinCompiler__Analysis.cmt"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/compiler/bitcoinCompiler__Analysis.cmx" {"compiler/bitcoinCompiler__Analysis.cmx"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/compiler/bitcoinCompiler__Utils.cmi" {"compiler/bitcoinCompiler__Utils.cmi"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/compiler/bitcoinCompiler__Utils.cmt" {"compiler/bitcoinCompiler__Utils.cmt"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/compiler/bitcoinCompiler__Utils.cmx" {"compiler/bitcoinCompiler__Utils.cmx"}
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/lib/bitcoin/opam" {"opam"}
]
bin: [
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/bin/bitcoin.compile" {"bitcoin.compile"}
]
doc: [
  "/Users/adrian/dev/kitto/kscript/bitcoin-compiler-simple/_esy/default/store/b/bitcoin-89d81627/install/default/doc/bitcoin/README.md"
]
