// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Script from "./Script.bs.js";

function complexOperation(param) {
  return Script.$neg(Script.$plus(5, 10), Script.$slash(3, 3));
}

export {
  complexOperation ,
  
}
/* No side effect */
